#!/bin/bash

if [ $# -eq 0  ]; then
    NAME="mongodb"
else 
    NAME=$1
fi

sudo docker run -it --name $NAME --rm --net="bridge" -p 27017:27017 -v /data/db:/data/db:z -v /mnt/nfs/logs:/var/log/mongodb:z -v /mnt/nfs/etc/mongo:/etc/mongo:z mongo:4.1.10-bionic
