#!/bin/bash

pwd=$(readlink -f $PWD)

if [ $# -eq 0 ]; then
    name="caidm"
else
    name=$1
fi

source activate gpu-full

# --- Add cnn modules
cd /home/$name/python/cnn
source ./setenv.sh cnn

# --- Add dl_utils
cd /home/$name/python/dl_utils
source ./setenv.sh

cd $HOME

jupyterhub --ip='*' -f $pwd/.jupyterhub_config.py
