#!/bin/bash

# ==================================
# USAGE
# ==================================
#
# >> ./docker-run-gpu-lite [name] [prefix], where:
# 
# [name]   = name of Docker container 
# [prefix] = prefix to /home folder(s)
#
# ==================================

# ==================================
# Set default context
# ==================================
if [ $# -eq 0 ]; then
    NAME="default"
    PREFIX=""

elif [ $# -eq 1 ]; then
    NAME=$1
    PREFIX=""

else
    NAME=$1
    PREFIX=$2
fi

if [ -d $PREFIX/data ]; then
    PREFIX_DATA=$PREFIX
else
    PREFIX_DATA=""
fi

# ==================================
# Run Docker 
# ==================================
sudo docker run --gpus all -it --rm -v /mnt:/mnt:Z -v $PREFIX/home:/home:Z -v $PREFIX_DATA/data:/data:Z -v $HOME/temp:/root/temp:Z -v $HOME/.Xauthority:/root/.Xauthority:Z --net="host" -e DISPLAY=$DISPLAY --name $NAME peterchang77/gpu-lite:1.0
