#!/bin/bash

# ==================================
# USAGE
# ==================================
#
# Must be run as root, however library must be public
#
# ==================================

jupyterhub --ip='*' -f $PWD/.jupyterhub_config.py
