# ======================================================================================
# INITIALIZE K8 CLUSTER WORKERS
# ======================================================================================
#
# (1) Determine k8 master token
#
# $ kubeadm token list
#
# (2) Determine k8 master hash
#
# $ sudo yum install -y openssl
# $ openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | \
#    openssl dgst -sha256 -hex | sed 's/^.* //'
#
# (3) Determine k8 master IP address / port
#
# (4) Run ansible playbook
#
# $ ansible-playbook install_k8_worker.yml --extra-vars 'k8_token=... k8_hash=... k8_host=... k8_port=...'
#
# ======================================================================================

- hosts: all 
  vars:
    k8_host:
    k8_port:
    k8_token: 
    k8_hash: 
  tasks:
  - name: Initialize worker 
    shell: kubeadm join --token {{ k8_token }} {{ k8_host }}:{{ k8_port }} --discovery-token-ca-cert-hash sha256:{{ k8_hash }}
    become: true
    become_method: sudo
