- hosts: master 
  tasks:
  - name: Initialize cluster 
    shell: kubeadm init --pod-network-cidr=10.244.0.0/16
    become: true
    become_method: sudo
  - name: Configure kubectl (make $HOME/.kube)
    file:
      path: "{{ ansible_env.HOME }}/.kube" 
      state: directory
  - name: Configure kubectl (copy template admin.conf)
    copy:
      remote_src: true
      src: "/etc/kubernetes/admin.conf"
      dest: "{{ ansible_env.HOME }}/.kube/config"
    become: true
    become_method: sudo
  - name: Configure kubectl (chown template admin.conf)
    file:
      path: "{{ ansible_env.HOME }}/.kube/config"
      owner: "{{ ansible_effective_user_id }}"
      group: "{{ ansible_effective_group_id }}"
    become: true
    become_method: sudo
  - name: Configure container network interface 
    shell: /usr/bin/kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
